In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('./ddanzi_total-2.tsv', encoding='utf-8', sep='\t\t', header=None, engine='python')

In [3]:
data.head()

,0,1,2,3,4,5
0,1,자유게시판 테스트중입니다 ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ...,관리자,2015-05-10,11.0,12500
1,2,음.. 안녕하세요,시다,2015-05-10,1.0,2479
2,3,자게이 난민 대피소인가요?,애러비,2015-05-10,NaN,2411
3,4,ㄷㄷㄷㄷㄷ여기가 디스트릭트9?,낮해밤달,2015-05-10,NaN,2541
4,5,아싸... 순위권 등극인가요?,아모피스,2015-05-10,NaN,2291

In [4]:
data.index

RangeIndex(start=0, stop=73717, step=1)

In [5]:
data.columns

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [6]:
df = data.loc[:,[1,2,3,4,5]].copy()

In [8]:
df.head()

,1,2,3,4,5
0,자유게시판 테스트중입니다 ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ...,관리자,2015-05-10,11.0,12500
1,음.. 안녕하세요,시다,2015-05-10,1.0,2479
2,자게이 난민 대피소인가요?,애러비,2015-05-10,NaN,2411
3,ㄷㄷㄷㄷㄷ여기가 디스트릭트9?,낮해밤달,2015-05-10,NaN,2541
4,아싸... 순위권 등극인가요?,아모피스,2015-05-10,NaN,2291

In [9]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
73687    False
73688    False
73689    False
73690    False
73691    False
73692    False
73693    False
73694    False
73695    False
73696    False
73697     True
73698    False
73699    False
73700    False
73701    False
73702    False
73703    False
73704    False
73705    False
73706    False
73707    False
73708    False
73709    False
73710    False
73711    False
73712    False
73713    False
73714    False
73715    False
73716    False
Length: 73717, dtype: bool

In [10]:
df = df.drop_duplicates()

In [11]:
df.head()

,1,2,3,4,5
0,자유게시판 테스트중입니다 ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ...,관리자,2015-05-10,11.0,12500
1,음.. 안녕하세요,시다,2015-05-10,1.0,2479
2,자게이 난민 대피소인가요?,애러비,2015-05-10,NaN,2411
3,ㄷㄷㄷㄷㄷ여기가 디스트릭트9?,낮해밤달,2015-05-10,NaN,2541
4,아싸... 순위권 등극인가요?,아모피스,2015-05-10,NaN,2291

In [12]:
df.groupby(2).count().sort_values([3], ascending=[False])

                  1     3    4     5
2
▶◀雨天           1167  1167  224  1167
나박사다            956   956   50   956
(˚∀˚)참치는TUNA    706   706   86   706
甲               641   641   26   641
후지지말입니다         586   586   50   586
꼼지오빠            554   554  124   554
석♥영             553   553  129   553
▶◀잠금몬           437   437   22   437
배부른기마민족         400   400  190   400
맬러뮤트보이          392   392   65   392
자연은블루베리         374   374   43   374
댓글관리위원회         368   368  100   368
s(*^-^)♡”       361   361   29   361
프레세페♥별          359   359   42   359
푸른무지개           350   350   37   350
눈떠보니중년          350   350   28   350
플로리에♥           339   339   35   339
Homopoeticus™   336   336   33   336
i오가사와라          315   315   12   315
순낚              310   310   63   310
프로디지♥           297   297   43   297
㈜예수             296   296   52   296
미확인몸짱           296   296   43   296
아기둘참치♥          294   294   14   294
십알삽입단♥          290   290   66   290
꺄륵POOH♥         290   290   16   290
친절한밀덕후™         287   287   61   287
riva128         271   271   17   271
현서®             269   269   50   269
이웃삼촌            258   258   23   258
...             ...   ...  ...   ...
몸짱될까              1     1    1     1
몸탐정코난             1     1    0     1
메렁스               1     1    0     1
멍뭉이다냥             1     1    0     1
말탄건달              1     1    1     1
멋진~               1     1    0     1
맑은나무              1     1    1     1
맘대로살리             1     1    0     1
망각의강              1     1    0     1
망구망구              1     1    0     1
망명로맨틱성공적          1     1    0     1
망명온자              1     1    0     1
망명자n              1     1    0     1
망자™               1     1    1     1
망한싸이트에서넘어온회원      1     1    1     1
맞고싶냐              1     1    0     1
맥뽕                1     1    0     1
맥스턴               1     1    0     1
맨날눈팅              1     1    0     1
맨도롱똣도             1     1    0     1
맨탈오브스틸™           1     1    1     1
맹뿌라브닭             1     1    0     1
머멈                1     1    0     1
머시마블루             1     1    0     1
머우야꼬              1     1    0     1
먹고자면살쪄            1     1    0     1
먹이사슬              1     1    1     1
먼개소리야             1     1    0     1
멀보나               1     1    0     1
😨기우뚱...           1     1    0     1

[6488 rows x 4 columns]

In [13]:
df.fillna(0)

,1,2,3,4,5
0,자유게시판 테스트중입니다 ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ...,관리자,2015-05-10,11.0,12500
1,음.. 안녕하세요,시다,2015-05-10,1.0,2479
2,자게이 난민 대피소인가요?,애러비,2015-05-10,0.0,2411
3,ㄷㄷㄷㄷㄷ여기가 디스트릭트9?,낮해밤달,2015-05-10,0.0,2541
4,아싸... 순위권 등극인가요?,아모피스,2015-05-10,0.0,2291
5,오오 여기가 여기가 ㄷㄷㄷㄷㄷㄷ,자연은블루베리,2015-05-10,0.0,2110
6,ㅎㄷㄷㄷㄷㄷㄷ,SiMCiTY,2015-05-10,0.0,1971
7,딴지에 자게라니 ㄷㄷ ㄷ ㄷ,행복한재호,2015-05-10,0.0,2119
8,여기가 자유게시판이 맞습니까? ㄷㄷㄷ,떡치기대장,2015-05-10,0.0,2027
9,ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ,▶◀고소한레고밥,2015-05-10,0.0,1998
10,#일본불매 #탐수아 #탐사영상,탐수아,2019-08-08,19.0,15126
11,서버 느려졌다.,읊조림,2015-05-10,0.0,1879
12,지금 서버 사러갑니다.,관리자,2015-05-10,6.0,39125
13,이렇게 느리면 나가린데........,wolfstudio,2015-05-10,0.0,1979
14,ㄷ ㄷ ㄷ ㄷ ㄷ ㄷ 일단 가입부터,Camion乃,2015-05-10,0.0,1771
15,SLR에서 이사왔습니다,퍄노,2015-05-10,0.0,1843
16,난민대피소 인가요??,토리™,2015-05-10,0.0,2081
17,일단 피난옴..,고굼,2015-05-10,0.0,1639
18,우워워~~~,인페,2015-05-10,0.0,1596
19,아무리 자게 난민촌이라지만 말이죠...,일격살충,2015-05-10,0.0,1698
20,서버 사러 갔답니다 서버 사오면 마저 놀아야지,대구사는오씨,2015-05-10,0.0,1638
21,사진 어캐 올림?,배부른기마민족,2015-05-10,0.0,1800
22,오메.. 글 함 남겨 봅니다요~!,심심햇,2015-05-10,0.0,1521
23,"..여긴 난민 수용소이긴 한데..환경이 열악함 ㅠㅡㅠ,,,",후지지말입니다,2015-05-10,0.0,1615
24,ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ,달군씨앗,2015-05-10,0.0,1434
25,난민 왔어유 ㄷㄷㄷ,뉴비-★,2015-05-10,0.0,1398
26,이쯤되면 양손에 서버끼고 총수가 격하게 환영해줘야되는거 아니오?,자연은블루베리,2015-05-10,0.0,1457
27,요기가 난민수용소인가요?,투명인간ㅠ.ㅠ,2015-05-10,0.0,1410
28,서버 증설을 위해 24:00 재부팅 합니다.,관리자,2015-05-10,1.0,6991
29,아직 순위권인듯요~!!,최파르타쿠스,2015-05-10,0.0,1345
...,...,...,...,...,...
73686,누님은 동생 뽕값 벌러 미국가시나보네요,지만이뽕값은누가내주나,2015-06-02,0.0,153
73687,쇼파도 as 가능한가요?,제시켜알바니까,2015-06-02,0.0,58
73688,정작 집을 사야할 사람들은 피 웃돈 주고 사야하고 돈은,화랑김,2015-06-02,0.0,81
73689,"어떤분이 올리신 알리발 성인용품(딜도)를 보고, 국산 딜도는 중국산보다 디테일한지 ...",누갤투어,2015-06-02,0.0,162
73690,망게 직원들 대부분이 여성분들이라네요,한계,2015-06-02,0.0,273
73691,한국인은 몽둥이로 패야해... ㅆㅂ,찰구,2015-06-02,0.0,309
73692,실질적으로 박대통령은 누구의 아바타일까요?,green&amp;red,2015-06-02,0.0,103
73693,"홍콩 당국.. ""격리 대상 한국인 남성, 홍콩으로 또 입국"".;;;;;",▶◀revolution▶◀,2015-06-02,0.0,388
73694,음모론좀 작작 좀 하시죠..보기 정말 싫네요.,휴켄,2015-06-02,0.0,279
73695,혐)경국지색..,파디,2015-06-02,1.0,458
73696,가뭄.. 역병.. 민생불안.. 민초들의 죽음,へ(￣⌒￣へ)맛있는씐나면,2015-06-02,0.0,70
73698,깨봉옹 있나여?ㄷㄷㄷ,아기둘참치♥,2015-06-02,0.0,65
73699,(출근조공)(달려라~달려) 단백질 교체작업 ^ㅡ^,스톰사마,2015-06-02,0.0,579
73700,출근이후 대화한마디도 안했어요;;,ㄷ등짝을보자ω,2015-06-02,0.0,188
73701,아놕...고래밥옹 만화가 공지에..ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ,cho7763,2015-06-02,0.0,189
73702,영국은 메르스 4명중에 3명이나 사망했군요..ㄷㄷ,울동네특공대,2015-06-02,0.0,311
73703,새로운 반공영화가 떴네요.,하얀나무,2015-06-02,0.0,263
73704,딴게분들을 초대하려 했는데...ㄷㄷ,행복마스터,2015-06-02,0.0,82
73705,"알베르토, KBS 새 요리예능 공동MC 발탁 ㄷㄷㄷ",ALEX™,2015-06-02,0.0,347
73706,".,.,...,,. 꼭 나올 ,.,. 기사.,., ㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷㄷ",맬러뮤트보이,2015-06-02,0.0,357
73707,메르스 덕분에 배달의 민족 기상을 드높이는군요,甲,2015-06-02,0.0,137
73708,어제 중국에 있엇던 돌풍,배부른기마민족,2015-06-02,1.0,358
73709,메르스의 진실.txt,へ(￣⌒￣へ)맛있는씐나면,2015-06-02,0.0,379
73710,유느님 종편 진출ㄷㄷㄷㄷㄷㄷ,부산빠순구,2015-06-02,0.0,412
73711,시발것들 하라는 건 안하고 별 좆같은 짓만 해대고 앉아 있네 시발 ㄷㄷㄷ,낭만변태,2015-06-02,1.0,105
73712,미크로겐 써보신분있나요,하부리,2015-06-02,0.0,31
73713,바다 즐기러 오세요 ㄷㄷㄷㄷㄷㄷ,행성X,2015-06-02,0.0,261
73714,정윤회 호칭은 영어로,국가대표선수,2015-06-02,0.0,132
73715,아크릴칼의 날은 어디서 갈면 되죠,복많은놈,2015-06-02,0.0,38
73716,동탄 메르스 난리. 초교 휴교 결정,abyssos,2015-06-02,0.0,488

In [15]:
df.to_csv("ddanzi-preprocess.tsv", mode='w', sep="|", header=None, index=None)